version: '3.8'

services:
  simple-web-server:
    container_name: simple-server
    image: devopsdockeruh/simple-web-service
    environment:
      - PORT=8000
    ports:
      - 8000:8000
    command: server
